Repository Arquisoft/viade_en2a, pull requests merged in 2020-05, with the labels that each got.

#196 Settings fix
  e2e/features/viewFriendRoutes.feature
  e2e/jest.config.js
  e2e/step-definitions/manageFriends.steps.js
  e2e/step-definitions/share.steps.js
  e2e/step-definitions/viewFriendRoutes.steps.js
  e2e2/manageFriends.steps.js
  e2e2/share.steps.js
  package.json
  public/index.html
  public/locales/en-US/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/notworking/addFriends.steps.js
  public/notworking/manageGroups.steps.js
  public/notworking/searchFriends.steps.js
  public/notworking/viewFriendRoutes.feature
  public/notworking/viewFriendRoutes.steps.js
  src/components/Notifications/children/Notifications/notifications.component.js
  src/components/Notifications/children/NotificationsPanel/children/NotificationItem/notification-item.component.js
  src/containers/CreateRoute/createRoute.container.js
  src/containers/ManageFriends/addFriend.component.js
  src/containers/ManageFriends/manageFriends.component.js
  src/containers/ManageFriends/manageFriends.container.js
  src/containers/ManageFriends/searchFriends.component.js
  src/containers/Map/LateralMenu/children/CommentsTab/CommentsForm/commentForm.component.js
  src/containers/Map/LateralMenu/children/CommentsTab/CommentsList/commentsList.component.js
  src/containers/Map/LateralMenu/children/CommentsTab/commentsTab.component.js
  src/containers/Map/LateralMenu/children/MultimediaTab/VinculationForm/vinculationForm.component.js
  src/containers/Map/LateralMenu/children/MultimediaTab/multimediaTab.component.js
  src/containers/Map/ShareButton/shareButton.component.js
  src/containers/Map/map.container.js
  src/containers/RouteList/routeList.container.js
  src/containers/Welcome/welcome.component.js
  src/containers/Welcome/welcome.container.js
  src/domain/domainClasses.js
  src/services/DomainJSONTranslator.js
  src/services/PODExtractor.js
  src/services/importing/gpx/gpxParser.js
  src/services/sharing.js
  src/utils/permissions.js
  src/utils/storage.js
Labels: Difficulty: challenging, Priority: Critical, Resolution: fixed

#191 Finished ttl to json parser and added condition to avoid badly create…
  package-lock.json
  package.json
  src/containers/CreateRoute/createRoute.container.js
  src/containers/RouteList/routeList.container.js
  src/services/DomainJSONTranslator.js
  src/services/PODExtractor.js
Labels: :heavy_plus_sign:enhancement, Difficulty: medium

#208 reduced zoom
  src/containers/Map/Map/map.component.js
Labels: Resolution: fixed

#215 add render test to view route
  src/__tests__/viewRouteTest.js
  src/containers/Map/LateralMenu/children/CommentsTab/commentsTab.component.js
  src/containers/Map/LateralMenu/children/DataTab/dataTab.component.js
  src/containers/Map/LateralMenu/children/MultimediaTab/multimediaTab.component.js
  src/containers/Map/LateralMenu/lateralMenu.component.js
Labels: :white_check_mark: Testing, Difficulty: starter

#216 view route test done
  src/__tests__/viewRouteTest.js
  src/containers/Map/LateralMenu/children/CommentsTab/commentsTab.component.js
  src/containers/Map/LateralMenu/children/DataTab/dataTab.component.js
  src/containers/Map/LateralMenu/children/MultimediaTab/multimediaTab.component.js
  src/containers/Map/LateralMenu/lateralMenu.component.js
Labels: :white_check_mark: Testing
